import { Outfit } from "next/font/google";
import { ClerkProvider, SignedOut, SignedIn, UserButton, SignInButton } from "@clerk/nextjs";

import "./globals.css";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>{children}
        {/* <header>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
